services:
  mongodb:
    image: mongo:latest
    container_name: bookmark_mongodb
    ports:
      - '27017:27017' # Expose MongoDB on default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - bookmark_data:/data/db # Persist MongoDB data

volumes:
  bookmark_data:
